---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io
      chart: cert-manager
      version: v1.14.4
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 24h0m0s
  targetNamespace: cert-manager
  install:
    createNamespace: true
  values:
    installCRDs: true
    clusterResourceNamespace: "kube-system"
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
    ingressShim:
      defaultIssuerName: "letsencrypt-prod"
      defaultIssuerKind: "ClusterIssuer"
      defaultIssuerGroup: "cert-manager.io"
