---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ambassador-certs
  namespace: ambassador
spec:
  secretName: ambassador-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - stiforr.com