---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 10.6.2
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  interval: 24h0m0s
  targetNamespace: traefik
  values:
    logs:
      general:
        level: ERROR
    ingressRoute:
      dashboard:
        enabled: true
        # Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class)
        annotations: { }
        # Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels)
        labels: { }
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
      minAvailable: 0
    ingressClass:
      enabled: true
      isDefaultClass: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        namespaces:
          [ ]
      kubernetesIngress:
        enabled: true
        namespaces:
          [ ]
        publishedService:
          enabled: false
    ports:
#      web:
#        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
          domains: [ ]
    globalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik"
    additionalArguments:
      - "--api=true"
      - "--api.dashboard=true"