---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 10.6.2
  install:
    createNamespace: true
  interval: 24h0m0s
  targetNamespace: traefik
  values:
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
      minAvailable: 0
    ingressClass:
      enabled: true
      isDefaultClass: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
          domains:
            - main: stiforr.com
    globalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik"