kind: Secret
apiVersion: v1
metadata:
    name: auth
    namespace: traefik
data:
    users: ENC[AES256_GCM,data:trh7fl8m94jCxnPhsQZgyo5mRBFEdT/P3w/dA99XmmSqF3cmpVtDPFp2qnMVpZP/Q3sh6PFMRFJeYufIEMe+rN2LXKEv4ZiYBbG9bA9YGMNj9wiQpb16KIlKpdxJpT0E,iv:moP8JSV2YHuz6GThiP+ofF1zCY+nf8O1Mw9drNr11eM=,tag:vHD2lSfToej5NzrYKJ9q6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-08T19:05:32Z"
    mac: ENC[AES256_GCM,data:+P38WolWwuYpJodR6vcR4xA8d+Vgl45fPLZbfBpAUbEWg6qi1a6V/pWW2gqvd8S39yW2kQrvKsFWSiAmXOSuYDwUknbmfW5LmVnEoA3kd4lA69RHZpva+4OX+sKzL3yOnuVXIUTo3eiWz1c5LCoA5usyBoKYCaXNj/mYu/Bqf5M=,iv:9KfavhwWYJqEK67CflBtQRX9AqViau4P7Qq+IFiwjfY=,tag:CgmkQwE3YxpLln5PZ9QuGg==,type:str]
    pgp:
        - created_at: "2021-12-08T19:05:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwbJWFCdJZWwAQ/9Gp8k7/+hnUEfV4XEJD9mM/uavE4SFS5qug4RT3P4YnMA
            L7FDlNC85rjXefFWMijX2T16/rZMmVnvDacPEg1pJi4aNQOvHEFR7OLB7flLIRld
            A2PbulHH83Y7/JQa4e25moB2v4+3N5JF/oQNZMJPPrqhbwr2wrjDmx8IAE19x75l
            AYbmNoO1NBlpYiGDAt1FNTr1QklkfU6sEkBJb8ZL5yYkrjL6BJtkkuH+OGbWbOJa
            TQqCs4an0cCvDMDiD3FfvbGmhVJ3izgTipiLDV7QGlLBAHP8PyFZNkdZeS11DD3U
            KMPPLumyomvdLQXPv3s1SQeqx+kVduFQuwBrTIk8FlXLaFQZFtFd1FxFE0daJxPt
            VT05RgT8mE4aDK9xs7Sr52+1Cg0nRprdFPVyBt4rWyHAB7Fuuvyz9JOHk5/KGLov
            EhUEepZpXPwp+zBI0ZcXK4Rr0goU0SJR4ZRipyWNl/pcyst9nXCyp6+tkOc05Hi2
            /jR+0ZFSTIQYjMpVsPz257P0ajVtIp6P2IYIA5GnieW0wd9Tglku2wMyCnbrddLQ
            2PiHiFU41EHtKqvSZHQDoWKCu1Pqm7oZN03wRKTOKgtzv9j4Nxg6PrnSjXYrtLGy
            BslOe0g1rYU0ATP9qANYq9AX+qkONzXaStAAbD1tOO2p4VBIZLirMpRpUhm/hE3S
            XgHbrhRj1yBC/oErcAfBvIyv0FrH06YQNVCvqcnZf0TwzVp08QRoT/jUqrhCAKTX
            /ZxfR00FBn0e+af4a14pkeVYfFniJRPrxRab22K6vgcwYtByU6rmNvVV81YPIfE=
            =2Syo
            -----END PGP MESSAGE-----
          fp: 1CD99ADC695765876E9B11658C3AE730765E27E7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
