apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: kube-system
data:
    cloudflare-email: ENC[AES256_GCM,data:AzMn/RPMr60UqIM63OeqVbcBA/m0IlSATZtJTX0kmWY=,iv:xeJbAwDE20YtbQS59UbkgIO8o7ZDVfvA6DT92DsDWRo=,tag:h7y0Hg3PX/YG2iHJfWdNdw==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:bqO0+YcCXqzJdhrBKod7qbzkV3KsEmQb1gZ6ll1RwGCqJwig9UnYGUajGMyFrju1gmd2FvKfIU4=,iv:g+BX3XFohJaw0Nqxjf5FUkl5eTx/Z8pyJPD8WQ+4g7Y=,tag:D8aSjlMs+EY/CN0hl6YFxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-09T02:40:26Z"
    mac: ENC[AES256_GCM,data:efHdKQb81N+L8JHMN+A8A9/a4eHj2i0agjXzceWBZnbW/wIJPjkMRZvcshpJXxN+4PaAZrh9tTTjK0vo2Ps4fmIiveuQ47+yso/DePCcte5WdpumDtC+0BZ0TLoRZmCo6TSsv8u8h6qScuVDwjDOvHbnf7KAxUgSBytvtG3OSlo=,iv:HIhWMZUdW3CLwN+aewERLeOUGgj13j1IcW0kz+r8Nus=,tag:mqhTiZ3hjHWT9k7ileymKA==,type:str]
    pgp:
        - created_at: "2021-11-09T02:21:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwbJWFCdJZWwAQ/+MF/c7Y2/+VcERo3zOqFJXK9j4M0Yaz7tjs3KtCkPIdDY
            xBTvgeSG6MunIIr0Oc0RZGrcU1Pvzt2RXXEymTsPGFZ+AuVUpMY9ueNXgUTZQoJm
            ZsCFUmkh00Z++BoC5+cugZxrxhAYc/m4t5d0hoBUcKAH0UITgWDC6F1Qfls1V918
            Hfq9XfZ4cWqinbuhpxGFcN2YtJLBa9pSD6I9YZH5afAEqQyGeevoa6ZdaZv3vEb+
            pZMRNuvLld3gJ0X2vs8LBlM4JfQtnXy6t6f8RDjO9QnHTtVWShI98lDU/N7OrEAH
            RLQWhJYDvL8BW0YVT1+kDU+b147jk9YuBmW2WveL7qepC7CbiejQRq2B0G7QRtLM
            DZmowPrWHIsI5WQGkm5nG2Fr3AfZix0vTnvcZE2dZWESdIt2enh1h6RMuxttzZn0
            Qlh2tQIu82N+svEnYjxUeBMMct6iZ2af2kFtGtEGQCuBvBs4LoJOS02pWb7kvKP/
            2QFqOL5r4v4xJCZm/VTup49G4xDqPkZhj8612SSDiTG7rkC2A4QMr1rGjGrstGBd
            lOZdAZj4ypAGfKuAYO3mEF2sKyw9Ft5IbzhYTP/De/t+wEKnrMndaE7hAR3Y2nhn
            kspOo7LLv61ypu54+bcfOYabrAJfznR4bpdgapcyS3y8JxiVS6o5JN3Kb0VN6DvS
            XgEBpUFPIdlZkK/N+Lu7EbueJJ2Iyd8/Rx1uR1gAfC4ed22a39m4lu80L6yVao4f
            J/bDEv6q0A6jNHfkUW4hze7JEmfDbezJ8o8GS69ck0XCrT/JHra7LWs9A02GxTU=
            =Dlzs
            -----END PGP MESSAGE-----
          fp: 1CD99ADC695765876E9B11658C3AE730765E27E7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
