---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wildstar
  namespace: ambassador
spec:
  hostname: "stiforr.com"
  selector:
    matchLabels:
      hostname: wildcard
  acmeProvider:
    authority: none
  tlsSecret:
    name: ambassador-certs
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-server
  namespace: argocd
spec:
  prefix: /argo-cd
  rewrite: /argo-cd
  service: argocd-server:443