---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argo-cd
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./cluster/infra/argo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system