---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: resources-tls
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./cluster/infra/resources/tls
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

