---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: resources-middleware
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./cluster/infra/resources/middleware
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

