---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sops-secrets
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./cluster/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

