name: e2e

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Setup Flux
        uses: fluxcd/flux2/action@main
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Install Flux in Kubernetes Kind
        run: flux install
      - name: Setup cluster reconciliation
        env:
          FLUX_IDENTITY: ${{ secrets.FLUX_IDENTITY }}
          FLUX_IDENTITY_PUB: ${{ secrets.FLUX_IDENTITY_PUB }}
          FLUX_KNOWN_HOSTS: ${{ secrets.FLUX_KNOWN_HOSTS }}
        run: |
          kubectl create secret generic flux-system \
          --from-literal=identity="${FLUX_IDENTITY}" \
          --from-literal=identity.pub="${FLUX_IDENTITY_PUB}" \
          --from-literal=known_hosts="${FLUX_KNOWN_HOSTS}"
          flux create source git flux-system \
          --url=${{ github.event.repository.html_url }} \
          --branch=main
          flux create kustomization flux-system \
          --source=flux-system \
          --path=./cluster/base
      - name: Verify cluster reconciliation
        run: |
          flux reconcile source git flux-system
          kubectl -n flux-system wait kustomization/argo-cd --for=condition=ready --timeout=10m
      - name: Verify helm reconciliation
        run: |
          kubectl -n default wait helmrelease/argo-cd --for=condition=ready --timeout=5m
      - name: Debug failure
        if: failure()
        run: |
          kubectl -n flux-system get all
          kubectl -n flux-system logs deploy/source-controller
          kubectl -n flux-system logs deploy/kustomize-controller
          kubectl -n flux-system logs deploy/helm-controller
          flux get all --all-namespaces